-- =====================================================================
-- EasyMoveDakar 
-- 96 lieux | 69 lignes | 108 arrêts | 315 liaisons ligne/arrêt
-- =====================================================================

-- ---------------------------------------------------------------------
-- LIEUX
-- ---------------------------------------------------------------------
INSERT INTO lieux (nom, type_lieu, latitude, longitude, description) VALUES
('Plateau', 'quartier', 14.6708, -17.4313, 'Centre administratif et économique de Dakar'),
('Médina', 'quartier', 14.6708, -17.4467, 'Quartier populaire et commerçant'),
('Colobane', 'quartier', 14.6812, -17.4423, 'Célèbre marché de la fripe et du commerce populaire'),
('Sandaga', 'quartier', 14.6737, -17.4344, 'Grand marché historique du centre-ville'),
('Tilène', 'quartier', 14.679, -17.446, 'Marché de quartier de la Médina'),
('Gueule Tapée', 'quartier', 14.68, -17.439, 'Quartier populaire proche de la Médina'),
('Fass', 'quartier', 14.685, -17.446, 'Quartier populaire, ancien village lébou'),
('Gorée', 'site_touristique', 14.6678, -17.3981, 'Île historique classée au patrimoine mondial de l''UNESCO'),
('Petersen', 'gare', 14.6759, -17.4373, 'Gare routière historique, terminus du réseau Tata/AFTU et départ du BRT'),
('Gare Routière Pompiers', 'gare', 14.7231, -17.4419, 'Principale gare routière pour les liaisons interurbaines'),
('Point E', 'quartier', 14.6928, -17.457, 'Quartier résidentiel et administratif'),
('Fann', 'quartier', 14.689, -17.464, 'Quartier résidentiel abritant l''hôpital et l''université'),
('UCAD', 'universite', 14.6928, -17.461, 'Université Cheikh Anta Diop'),
('Amitié', 'quartier', 14.695, -17.462, 'Quartier résidentiel de Fann-Point E-Amitié'),
('Bopp', 'quartier', 14.687, -17.453, 'Quartier populaire proche de la Corniche'),
('Mermoz', 'quartier', 14.704, -17.47, 'Quartier résidentiel en bord de mer'),
('Sacré-Cœur', 'quartier', 14.7186, -17.4638, 'Quartier résidentiel desservi par le BRT, proche de la VDN'),
('Castors', 'quartier', 14.708, -17.437, 'Quartier résidentiel proche de la Gare'),
('Grand Dakar', 'quartier', 14.707, -17.447, 'Quartier populaire et commerçant'),
('Biscuiterie', 'quartier', 14.703, -17.442, 'Quartier populaire du centre'),
('HLM', 'quartier', 14.701, -17.445, 'Grand quartier d''habitat, marché HLM réputé'),
('Dieuppeul', 'quartier', 14.713, -17.449, 'Quartier résidentiel'),
('Derklé', 'quartier', 14.715, -17.452, 'Quartier résidentiel proche de Dieuppeul'),
('Liberté 1', 'quartier', 14.698, -17.447, 'Cité Liberté, secteur 1'),
('Liberté 2', 'quartier', 14.7, -17.449, 'Cité Liberté, secteur 2'),
('Liberté 3', 'quartier', 14.702, -17.451, 'Cité Liberté, secteur 3'),
('Liberté 4', 'quartier', 14.704, -17.453, 'Cité Liberté, secteur 4'),
('Liberté 5', 'quartier', 14.706, -17.455, 'Cité Liberté, secteur 5'),
('Liberté 6', 'quartier', 14.711, -17.4577, 'Carrefour important, rond-point Liberté 6'),
('Sicap Baobab', 'quartier', 14.718, -17.455, 'Cité Sicap, secteur Baobab'),
('Sicap Amitié', 'quartier', 14.7, -17.46, 'Cité Sicap, secteur Amitié'),
('Sicap Karack', 'quartier', 14.71, -17.452, 'Cité Sicap, secteur Karack'),
('Front de Terre', 'quartier', 14.722, -17.447, 'Quartier populaire densément peuplé'),
('Hann', 'quartier', 14.722, -17.429, 'Quartier historique en bord de baie'),
('Hann Bel-Air', 'quartier', 14.728, -17.434, 'Quartier résidentiel et industriel'),
('Hann Maristes', 'quartier', 14.718, -17.42, 'Quartier résidentiel proche de Hann'),
('Grand Yoff', 'quartier', 14.7364, -17.4569, 'Quartier populaire densément peuplé'),
('Patte d''Oie', 'quartier', 14.729, -17.448, 'Carrefour routier majeur du nord de Dakar'),
('Zone de Captage', 'quartier', 14.735, -17.46, 'Quartier résidentiel proche de Grand Yoff'),
('Cité Keur Gorgui', 'quartier', 14.729, -17.47, 'Quartier d''affaires récent proche de la VDN'),
('Ouakam', 'quartier', 14.7167, -17.4833, 'Quartier proche de la Mosquée de la Divinité'),
('Mamelles', 'quartier', 14.727, -17.493, 'Quartier du phare des Mamelles'),
('Virage Ouakam', 'quartier', 14.72, -17.478, 'Carrefour de la corniche ouest'),
('Ngor', 'quartier', 14.7508, -17.5133, 'Village de pêcheurs, embarcadère pour l''île de Ngor'),
('Almadies', 'quartier', 14.7472, -17.5136, 'Quartier résidentiel et zone de restaurants / vie nocturne'),
('Yoff', 'quartier', 14.7444, -17.4677, 'Quartier balnéaire et village lébou'),
('Yoff Tonghor', 'quartier', 14.748, -17.472, 'Secteur traditionnel du village de Yoff'),
('Ouest Foire', 'quartier', 14.742, -17.475, 'Quartier résidentiel proche de l''aéroport LSS'),
('Nord Foire', 'quartier', 14.7461, -17.4826, 'Quartier proche du Centre International du Commerce Extérieur'),
('Cambérène', 'quartier', 14.755, -17.457, 'Quartier populaire, foyer historique de la confrérie layène'),
('Parcelles Assainies', 'quartier', 14.7565, -17.436, 'Vaste zone résidentielle, carrefour de plusieurs lignes de minibus'),
('Grand Médine', 'quartier', 14.748, -17.44, 'Quartier populaire proche des Parcelles Assainies'),
('Golf Sud', 'quartier', 14.762, -17.423, 'Commune de Guédiawaye'),
('Golf', 'quartier', 14.765, -17.41, 'Quartier résidentiel de Guédiawaye'),
('Wakhinane', 'quartier', 14.778, -17.405, 'Commune de Guédiawaye'),
('Médina Gounass', 'quartier', 14.775, -17.415, 'Commune de Guédiawaye'),
('Guédiawaye', 'quartier', 14.7692, -17.4036, 'Commune de la banlieue nord de Dakar'),
('Pikine', 'quartier', 14.7547, -17.39, 'Grande commune de la banlieue de Dakar'),
('Pikine Nord', 'quartier', 14.765, -17.398, 'Commune de Pikine'),
('Pikine Est', 'quartier', 14.758, -17.385, 'Commune de Pikine'),
('Guinaw Rail', 'quartier', 14.75, -17.398, 'Quartier populaire de Pikine, le long de l''ancienne voie ferrée'),
('Dalifort', 'quartier', 14.735, -17.415, 'Commune proche de l''autoroute, entre Dakar et Pikine'),
('Yeumbeul', 'quartier', 14.77, -17.365, 'Commune de la banlieue est'),
('Djidah Thiaroye Kao', 'quartier', 14.755, -17.37, 'Commune de Pikine'),
('Thiaroye', 'quartier', 14.7639, -17.3592, 'Commune de la banlieue est'),
('Thiaroye Gare', 'quartier', 14.76, -17.365, 'Ancienne gare ferroviaire, quartier historique'),
('Thiaroye sur Mer', 'quartier', 14.753, -17.375, 'Quartier de pêcheurs en bord de mer'),
('Malika', 'quartier', 14.785, -17.355, 'Commune du littoral nord, plage réputée'),
('Keur Massar', 'ville', 14.7833, -17.3167, 'Chef-lieu du département de Keur Massar'),
('Petit Mbao', 'quartier', 14.74, -17.33, 'Quartier résidentiel proche de Mbao'),
('Mbao', 'quartier', 14.735, -17.335, 'Commune proche de la zone industrielle'),
('Grand Mbao', 'quartier', 14.7492, -17.3178, 'Zone industrielle et résidentielle à l''est de Dakar'),
('Diacksao', 'quartier', 14.745, -17.355, 'Quartier entre Pikine et Keur Massar'),
('Rufisque', 'ville', 14.7167, -17.2667, 'Ville historique à l''entrée de Dakar'),
('Rufisque Nord', 'quartier', 14.725, -17.27, 'Commune de Rufisque'),
('Rufisque Est', 'quartier', 14.71, -17.255, 'Commune de Rufisque'),
('Bargny', 'ville', 14.6969, -17.2214, 'Ville industrielle et portuaire'),
('Diamniadio', 'ville', 14.7167, -17.1833, 'Nouvelle ville en développement, desservie par le TER'),
('Sébikotane', 'ville', 14.75, -17.1333, 'Ville industrielle proche de Diamniadio'),
('Sangalkam', 'ville', 14.7833, -17.2333, 'Commune rurale entre Rufisque et Keur Massar'),
('Bambilor', 'ville', 14.8167, -17.25, 'Commune rurale du département de Rufisque'),
('Yenne', 'ville', 14.7167, -17.0833, 'Commune historique à l''entrée sud de la Petite Côte'),
('Lac Rose (Retba)', 'site_touristique', 14.8402, -17.2306, 'Lac rose classé au patrimoine, site touristique majeur'),
('Aéroport AIBD', 'aeroport', 14.6704, -17.073, 'Aéroport International Blaise Diagne'),
('Cité Comico', 'quartier', 14.715, -17.446, 'Quartier résidentiel proche de Grand Dakar'),
('Yarakh', 'quartier', 14.7, -17.418, 'Quartier populaire en bord de baie de Hann'),
('Fenêtre Mermoz', 'quartier', 14.706, -17.468, 'Secteur de Mermoz proche de la Corniche'),
('Marché HLM', 'quartier', 14.7005, -17.4455, 'Marché textile réputé du quartier HLM'),
('Cité Assemblée', 'quartier', 14.735, -17.468, 'Quartier résidentiel proche de Grand Yoff'),
('Sicap Liberté', 'quartier', 14.7005, -17.45, 'Cité Sicap centrale'),
('Baobab', 'quartier', 14.716, -17.456, 'Secteur de Sicap Baobab'),
('Terminus Ouakam', 'quartier', 14.715, -17.482, 'Terminus des lignes desservant Ouakam'),
('Cité Aliou Sow', 'quartier', 14.737, -17.365, 'Quartier résidentiel de Thiaroye'),
('Cité Millionnaire', 'quartier', 14.746, -17.345, 'Quartier résidentiel proche de Mbao'),
('Diokoul', 'quartier', 14.71, -17.26, 'Quartier populaire de Rufisque'),
('Arafat', 'quartier', 14.73, -17.275, 'Quartier de Rufisque');

-- ---------------------------------------------------------------------
-- MOYENS_TRANSPORT
-- ---------------------------------------------------------------------
INSERT INTO moyens_transport (nom, image_url, description, cout_min, cout_max, niveau_confort, disponibilite, avantages, inconvenients) VALUES
('Taxi clando', '/static/img/taxi.jpg', 'Taxi de ville jaune et noir, prix à négocier', 500, 2000, 'Moyen', '24h/24', 'Rapide, disponible partout, porte-à-porte', 'Prix à négocier, confort variable, pas de compteur'),
('Dakar Dem Dikk', '/static/img/DDD.jpg', 'Bus officiel de la ville de Dakar (DDD), lignes numérotées et tarif fixe — opérateur public, distinct du réseau Tata/AFTU', 150, 300, 'Moyen', '6h - 22h', 'Prix fixe et abordable, réseau étendu', 'Peut être bondé aux heures de pointe, moins flexible'),
('Car rapide', '/static/img/Car_rapide.jpg', 'Minibus artisanal coloré, emblème populaire du transport à Dakar', 100, 200, 'Faible', 'Selon affluence', 'Très bon marché, expérience authentique', 'Confort limité, pas d''horaires fixes'),
('Minibus Tata (AFTU)', '/static/img/mini_bus.jpg', 'Réseau de minibus numérotés géré par l''AFTU, dessert la quasi-totalité des communes de Dakar (une soixantaine de lignes)', 100, 500, 'Faible', 'Tôt le matin - tard le soir, selon affluence', 'Très bon marché, réseau très dense, dessert presque tous les quartiers', 'Bondé aux heures de pointe, pas d''horaires fixes, numéros parfois difficiles à repérer'),
('Jakarta (moto-taxi)', '/static/img/moto.jpg', 'Moto-taxi rapide pour se faufiler dans les embouteillages', 300, 1500, 'Faible', '24h/24', 'Très rapide en cas d''embouteillages, économique', 'Moins sécurisant, casque pas toujours fourni'),
('TER', '/static/img/TER.jpg', 'Train Express Régional reliant Dakar à Diamniadio et à l''aéroport AIBD (extension vers Thiès prévue pour 2027-2028)', 500, 2500, 'Élevé', '5h30 - 22h30', 'Rapide, climatisé, ponctuel, prix fixe', 'Dessert un nombre limité de gares'),
('BRT (Bus Rapid Transit)', '/static/img/BRT.jpg', 'Bus électrique à haut niveau de service en site propre, reliant Petersen à la préfecture de Guédiawaye (lignes B1 et B2), mis en service en 2024', 400, 500, 'Élevé', '6h - 21h (7j/7)', 'Ponctuel, climatisé, fréquence de 6 minutes, embarquement au niveau du quai', 'Couvre pour l''instant un seul axe (Petersen - Guédiawaye)');

-- ---------------------------------------------------------------------
-- LIGNES_BUS
-- ---------------------------------------------------------------------
INSERT INTO lignes_bus (numero_ligne, nom_ligne, id_transport, est_minibus, description) VALUES
('Ligne 7', 'Plateau - Pikine', 2, 0, 'Dakar Dem Dikk reliant Plateau à Pikine Est via Colobane, Grand Dakar, Dalifort, Pikine'),
('Ligne 9', 'Plateau - Guédiawaye', 2, 0, 'Dakar Dem Dikk reliant Plateau à Guédiawaye via HLM, Front de Terre, Parcelles Assainies, Golf'),
('Ligne 14', 'Plateau - UCAD', 2, 0, 'Dakar Dem Dikk reliant Plateau à UCAD via Bopp, Fann'),
('Ligne 18', 'Plateau - Rufisque', 2, 0, 'Dakar Dem Dikk reliant Plateau à Rufisque via Hann, Thiaroye, Rufisque Nord'),
('Ligne 22', 'Petersen - Ouakam', 2, 0, 'Dakar Dem Dikk reliant Petersen à Ouakam via Point E, Fann, Mermoz'),
('Ligne 25', 'Plateau - Keur Massar', 2, 0, 'Dakar Dem Dikk reliant Plateau à Keur Massar via Grand Dakar, Pikine, Yeumbeul'),
('Ligne 28', 'Petersen - Diamniadio', 2, 0, 'Dakar Dem Dikk reliant Petersen à Diamniadio via Grand Mbao, Bargny'),
('B1', 'Petersen - Préfecture de Guédiawaye (Omnibus)', 7, 0, 'BRT (Bus Rapid Transit) reliant Petersen à Guédiawaye via Grand Dakar, Sacré-Cœur, Front de Terre, Patte d''Oie, Parcelles Assainies, Golf Sud'),
('B2', 'Petersen - Préfecture de Guédiawaye (Semi-express)', 7, 0, 'BRT (Bus Rapid Transit) reliant Petersen à Guédiawaye via Sacré-Cœur, Patte d''Oie, Golf Sud'),
('TER', 'Dakar - AIBD', 6, 0, 'TER reliant Petersen à Aéroport AIBD via Hann, Diamniadio, Sébikotane'),
('CR-1', 'Petersen - Rufisque (Car rapide)', 3, 1, 'Car rapide reliant Petersen à Rufisque via Colobane, Hann Bel-Air, Thiaroye'),
('CR-2', 'Sandaga - Ouakam (Car rapide)', 3, 1, 'Car rapide reliant Sandaga à Ouakam via Médina, Bopp, Fann'),
('CR-3', 'Petersen - Pikine (Car rapide)', 3, 1, 'Car rapide reliant Petersen à Pikine via Colobane, Grand Dakar, Dalifort'),
('CR-4', 'Médina - Grand Yoff (Car rapide)', 3, 1, 'Car rapide reliant Médina à Grand Yoff via Fass, HLM, Grand Dakar'),
('Ligne 1', 'Petersen - Yeumbeul', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Yeumbeul via Colobane, Grand Dakar, Dalifort, Pikine, Guinaw Rail'),
('Ligne 2', 'Sandaga - Malika', 4, 1, 'Minibus Tata (AFTU) reliant Sandaga à Malika via Colobane, Cambérène, Thiaroye sur Mer'),
('Ligne 3', 'Petersen - Yoff Village (via Ouakam, Mamelles)', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Yoff via Bopp, Fann, Ouakam, Mamelles'),
('Ligne 4', 'Petersen - Yoff Village (via VDN)', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Yoff via Sacré-Cœur, Cité Keur Gorgui, Ouest Foire'),
('Ligne 5', 'Colobane - Grand Yoff', 4, 1, 'Minibus Tata (AFTU) reliant Colobane à Grand Yoff via HLM, Biscuiterie, Dieuppeul'),
('Ligne 6', 'Médina - Liberté 6', 4, 1, 'Minibus Tata (AFTU) reliant Médina à Liberté 6 via Fass, Liberté 1, Liberté 3'),
('Ligne 8', 'Petersen - Front de Terre', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Front de Terre via Grand Dakar, Biscuiterie'),
('Ligne 10', 'Sandaga - Hann', 4, 1, 'Minibus Tata (AFTU) reliant Sandaga à Hann Bel-Air via Colobane, Hann'),
('Ligne 11', 'Médina - Point E', 4, 1, 'Minibus Tata (AFTU) reliant Médina à Point E via Tilène, Fass'),
('Ligne 12', 'Petersen - Sicap Baobab', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Sicap Baobab via Liberté 2, Sicap Karack'),
('Ligne 13', 'Colobane - Derklé', 4, 1, 'Minibus Tata (AFTU) reliant Colobane à Derklé via HLM, Dieuppeul'),
('Ligne 15', 'Petersen - Almadies', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Almadies via Liberté 5, Sacré-Cœur, Mermoz, Ngor'),
('Ligne 16', 'Sandaga - Zone de Captage', 4, 1, 'Minibus Tata (AFTU) reliant Sandaga à Zone de Captage via Grand Dakar, Grand Yoff'),
('Ligne 17', 'Médina - Patte d''Oie', 4, 1, 'Minibus Tata (AFTU) reliant Médina à Patte d''Oie via Fass, Grand Dakar'),
('Ligne 19', 'Petersen - Cambérène', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Cambérène via Grand Yoff, Grand Médine, Parcelles Assainies'),
('Ligne 20', 'Colobane - Nord Foire', 4, 1, 'Minibus Tata (AFTU) reliant Colobane à Nord Foire via Front de Terre, Zone de Captage, Ouest Foire'),
('Ligne 21', 'Petersen - Yoff Tonghor', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Yoff Tonghor via Sacré-Cœur, Ouest Foire, Yoff'),
('Ligne 24', 'Grand Yoff - Parcelles Assainies', 4, 1, 'Minibus Tata (AFTU) reliant Grand Yoff à Parcelles Assainies via Zone de Captage, Grand Médine'),
('Ligne 26', 'Petersen - Golf', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Golf via Patte d''Oie, Parcelles Assainies, Golf Sud'),
('Ligne 27', 'Colobane - Dalifort', 4, 1, 'Minibus Tata (AFTU) reliant Colobane à Dalifort via Grand Dakar, Hann Bel-Air'),
('Ligne 29', 'Petersen - Thiaroye Gare', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Thiaroye Gare via Hann Bel-Air, Dalifort, Pikine'),
('Ligne 30', 'Sandaga - Guinaw Rail', 4, 1, 'Minibus Tata (AFTU) reliant Sandaga à Guinaw Rail via Colobane, Dalifort, Pikine'),
('Ligne 32', 'Médina - Sicap Amitié', 4, 1, 'Minibus Tata (AFTU) reliant Médina à Sicap Amitié via Bopp, Amitié'),
('Ligne 34', 'Petersen - Nord Foire (via Gueule Tapée, Rue 10)', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Nord Foire via Gueule Tapée, Fann, Point E, Ouest Foire'),
('Ligne 36', 'Ngor - Guédiawaye (via Parcelles Assainies)', 4, 1, 'Minibus Tata (AFTU) reliant Ngor à Guédiawaye via Yoff, Cambérène, Parcelles Assainies, Golf Sud'),
('Ligne 38', 'Colobane - Wakhinane', 4, 1, 'Minibus Tata (AFTU) reliant Colobane à Wakhinane via Front de Terre, Parcelles Assainies, Médina Gounass'),
('Ligne 39', 'Petersen - Djidah Thiaroye Kao', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Djidah Thiaroye Kao via Grand Dakar, Pikine'),
('Ligne 40', 'Petersen - Grand Mbao (via Hann Maristes)', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Grand Mbao via Hann, Hann Maristes, Petit Mbao'),
('Ligne 41', 'Guédiawaye - Malika', 4, 1, 'Minibus Tata (AFTU) reliant Guédiawaye à Malika via Wakhinane, Yeumbeul'),
('Ligne 42', 'Pikine - Djidah Thiaroye Kao', 4, 1, 'Minibus Tata (AFTU) reliant Pikine à Djidah Thiaroye Kao via Guinaw Rail'),
('Ligne 43', 'Ouakam - Thiaroye (via Grand Dakar)', 4, 1, 'Minibus Tata (AFTU) reliant Ouakam à Thiaroye via Virage Ouakam, Grand Dakar, Dalifort, Pikine'),
('Ligne 44', 'Ouakam - Grand Mbao (via VDN)', 4, 1, 'Minibus Tata (AFTU) reliant Ouakam à Grand Mbao via Mermoz, Sacré-Cœur, Front de Terre, Petit Mbao'),
('Ligne 45', 'Keur Massar - Malika', 4, 1, 'Minibus Tata (AFTU) reliant Keur Massar à Malika via Diacksao, Yeumbeul'),
('Ligne 46', 'Petersen - Guédiawaye (via Pikine, Liberté, Bourguiba)', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Guédiawaye via Liberté 4, Grand Dakar, Pikine, Golf'),
('Ligne 47', 'Petersen - Almadies (via Grand Yoff)', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Almadies via Grand Yoff, Zone de Captage, Ouest Foire'),
('Ligne 48', 'Rufisque - Bargny', 4, 1, 'Minibus Tata (AFTU) reliant Rufisque à Bargny via Rufisque Est'),
('Ligne 49', 'Rufisque - Sangalkam', 4, 1, 'Minibus Tata (AFTU) reliant Rufisque à Sangalkam via Rufisque Nord'),
('Ligne 50', 'Diamniadio - Sébikotane', 4, 1, 'Minibus Tata (AFTU) reliant Diamniadio à Sébikotane'),
('Ligne 52', 'Keur Massar - Sangalkam', 4, 1, 'Minibus Tata (AFTU) reliant Keur Massar à Sangalkam via Diacksao'),
('Ligne 53', 'Pikine - Keur Massar', 4, 1, 'Minibus Tata (AFTU) reliant Pikine à Keur Massar via Djidah Thiaroye Kao, Diacksao'),
('Ligne 55', 'Thiaroye - Keur Massar', 4, 1, 'Minibus Tata (AFTU) reliant Thiaroye à Keur Massar via Thiaroye Gare, Diacksao'),
('Ligne 56', 'Guédiawaye - Keur Massar', 4, 1, 'Minibus Tata (AFTU) reliant Guédiawaye à Keur Massar via Wakhinane, Médina Gounass'),
('Ligne 57', 'Bambilor - Sangalkam', 4, 1, 'Minibus Tata (AFTU) reliant Bambilor à Sangalkam'),
('Ligne 58', 'Sangalkam - Yenne', 4, 1, 'Minibus Tata (AFTU) reliant Sangalkam à Yenne via Bargny'),
('Ligne 60', 'Rufisque - Diamniadio', 4, 1, 'Minibus Tata (AFTU) reliant Rufisque à Diamniadio via Rufisque Est, Bargny'),
('Ligne 63', 'Colobane - Lac Rose', 4, 1, 'Minibus Tata (AFTU) reliant Colobane à Lac Rose (Retba) via Guinaw Rail, Malika'),
('Ligne 64', 'Golf - Malika', 4, 1, 'Minibus Tata (AFTU) reliant Golf à Malika via Wakhinane, Yeumbeul'),
('Ligne 65', 'Sandaga - Fann', 4, 1, 'Minibus Tata (AFTU) reliant Sandaga à Fann via Colobane, Fass, Point E'),
('Ligne 66', 'Colobane - Sicap Karack', 4, 1, 'Minibus Tata (AFTU) reliant Colobane à Sicap Karack via Liberté 1, Liberté 2'),
('Ligne 67', 'Ouakam - Rufisque (via Bourguiba)', 4, 1, 'Minibus Tata (AFTU) reliant Ouakam à Rufisque via Virage Ouakam, Hann Bel-Air, Thiaroye'),
('Ligne 70', 'Petersen - Castors', 4, 1, 'Minibus Tata (AFTU) reliant Petersen à Castors via Colobane, Biscuiterie'),
('Ligne 72', 'Médina - Gorée (embarcadère)', 4, 1, 'Minibus Tata (AFTU) reliant Médina à Gorée via Plateau'),
('Ligne 75', 'Ouest Foire - Cité Keur Gorgui', 4, 1, 'Minibus Tata (AFTU) reliant Ouest Foire à Sacré-Cœur via Nord Foire, Cité Keur Gorgui'),
('Ligne 78', 'Grand Yoff - Cambérène', 4, 1, 'Minibus Tata (AFTU) reliant Grand Yoff à Cambérène via Zone de Captage, Parcelles Assainies'),
('Ligne 80', 'Parcelles Assainies - Yeumbeul', 4, 1, 'Minibus Tata (AFTU) reliant Parcelles Assainies à Yeumbeul via Golf Sud, Guédiawaye');

-- ---------------------------------------------------------------------
-- ARRETS
-- ---------------------------------------------------------------------
INSERT INTO arrets (nom, id_lieu, latitude, longitude) VALUES
('Place de l''Indépendance', 1, 14.6708, -17.4313),
('Sandaga - Quai Nord', 1, 14.6716, -17.4318),
('Poste Médina', 2, 14.6708, -17.4467),
('Marché Colobane', 3, 14.6812, -17.4423),
('Colobane - Gare', 3, 14.6805, -17.4429),
('Marché Sandaga', 4, 14.6737, -17.4344),
('Sandaga - Quai Sud', 4, 14.6731, -17.4336),
('Marché Tilène', 5, 14.679, -17.446),
('Arrêt Gueule Tapée', 6, 14.68, -17.439),
('Arrêt Fass', 7, 14.685, -17.446),
('Embarcadère Gorée', 8, 14.6678, -17.3981),
('Petersen - Gare Routière', 9, 14.6759, -17.4373),
('Petersen - Quai BRT', 9, 14.6768, -17.4367),
('Petersen - Quai Tata', 9, 14.6752, -17.4363),
('Gare Routière Pompiers', 10, 14.7231, -17.4419),
('Arrêt Point E', 11, 14.6928, -17.457),
('Arrêt Fann', 12, 14.689, -17.464),
('UCAD Étudiants', 13, 14.6928, -17.461),
('Arrêt Amitié', 14, 14.695, -17.462),
('Arrêt Bopp', 15, 14.687, -17.453),
('Arrêt Mermoz', 16, 14.704, -17.47),
('Station Sacré-Cœur (BRT)', 17, 14.7186, -17.4638),
('Arrêt Castors', 18, 14.708, -17.437),
('Arrêt Grand Dakar', 19, 14.707, -17.447),
('Grand Dakar - Marché', 19, 14.7077, -17.4464),
('Arrêt Biscuiterie', 20, 14.703, -17.442),
('Arrêt HLM', 21, 14.701, -17.445),
('Arrêt Dieuppeul', 22, 14.713, -17.449),
('Arrêt Derklé', 23, 14.715, -17.452),
('Arrêt Liberté 1', 24, 14.698, -17.447),
('Arrêt Liberté 2', 25, 14.7, -17.449),
('Arrêt Liberté 3', 26, 14.702, -17.451),
('Arrêt Liberté 4', 27, 14.704, -17.453),
('Arrêt Liberté 5', 28, 14.706, -17.455),
('Rond-point Liberté 6', 29, 14.711, -17.4577),
('Arrêt Sicap Baobab', 30, 14.718, -17.455),
('Arrêt Sicap Amitié', 31, 14.7, -17.46),
('Arrêt Sicap Karack', 32, 14.71, -17.452),
('Arrêt Front de Terre', 33, 14.722, -17.447),
('Arrêt Hann', 34, 14.722, -17.429),
('Arrêt Hann Bel-Air', 35, 14.728, -17.434),
('Arrêt Hann Maristes', 36, 14.718, -17.42),
('Carrefour Grand Yoff', 37, 14.7364, -17.4569),
('Carrefour Grand Yoff - Quai 2', 37, 14.7372, -17.4575),
('Arrêt Patte d''Oie', 38, 14.729, -17.448),
('Arrêt Zone de Captage', 39, 14.735, -17.46),
('Arrêt Cité Keur Gorgui', 40, 14.729, -17.47),
('Rond-point Ouakam', 41, 14.7167, -17.4833),
('Arrêt Mamelles', 42, 14.727, -17.493),
('Arrêt Virage Ouakam', 43, 14.72, -17.478),
('Ngor Village', 44, 14.7508, -17.5133),
('Almadies - VDN', 45, 14.7472, -17.5136),
('Yoff Village', 46, 14.7444, -17.4677),
('Arrêt Yoff Tonghor', 47, 14.748, -17.472),
('Arrêt Ouest Foire', 48, 14.742, -17.475),
('Terminus Nord Foire', 49, 14.7461, -17.4826),
('Arrêt Cambérène', 50, 14.755, -17.457),
('Terminus Parcelles Assainies', 51, 14.7565, -17.436),
('Parcelles - Unité 15', 51, 14.7577, -17.4351),
('Parcelles - Unité 1', 51, 14.7555, -17.4367),
('Arrêt Grand Médine', 52, 14.748, -17.44),
('Arrêt Golf Sud', 53, 14.762, -17.423),
('Arrêt Golf', 54, 14.765, -17.41),
('Arrêt Wakhinane', 55, 14.778, -17.405),
('Arrêt Médina Gounass', 56, 14.775, -17.415),
('Préfecture de Guédiawaye', 57, 14.7692, -17.4036),
('Guédiawaye - Gare Routière', 57, 14.7684, -17.4029),
('Arrêt Pikine', 58, 14.7547, -17.39),
('Pikine - Gare Routière', 58, 14.7556, -17.3908),
('Arrêt Pikine Nord', 59, 14.765, -17.398),
('Arrêt Pikine Est', 60, 14.758, -17.385),
('Arrêt Guinaw Rail', 61, 14.75, -17.398),
('Arrêt Dalifort', 62, 14.735, -17.415),
('Arrêt Yeumbeul', 63, 14.77, -17.365),
('Arrêt Djidah Thiaroye Kao', 64, 14.755, -17.37),
('Terminus Thiaroye', 65, 14.7639, -17.3592),
('Arrêt Thiaroye Gare', 66, 14.76, -17.365),
('Arrêt Thiaroye sur Mer', 67, 14.753, -17.375),
('Arrêt Malika', 68, 14.785, -17.355),
('Arrêt Keur Massar', 69, 14.7833, -17.3167),
('Arrêt Petit Mbao', 70, 14.74, -17.33),
('Arrêt Mbao', 71, 14.735, -17.335),
('Terminus Grand Mbao', 72, 14.7492, -17.3178),
('Arrêt Diacksao', 73, 14.745, -17.355),
('Gare Routière Rufisque', 74, 14.7167, -17.2667),
('Rufisque - Marché', 74, 14.7175, -17.266),
('Arrêt Rufisque Nord', 75, 14.725, -17.27),
('Arrêt Rufisque Est', 76, 14.71, -17.255),
('Arrêt Bargny', 77, 14.6969, -17.2214),
('Gare TER Diamniadio', 78, 14.7167, -17.1833),
('Arrêt Sébikotane', 79, 14.75, -17.1333),
('Arrêt Sangalkam', 80, 14.7833, -17.2333),
('Arrêt Bambilor', 81, 14.8167, -17.25),
('Arrêt Yenne', 82, 14.7167, -17.0833),
('Lac Rose - Embarcadère', 83, 14.8402, -17.2306),
('Gare TER AIBD', 84, 14.6704, -17.073),
('Arrêt Cité Comico', 85, 14.715, -17.446),
('Arrêt Yarakh', 86, 14.7, -17.418),
('Arrêt Fenêtre Mermoz', 87, 14.706, -17.468),
('Arrêt Marché HLM', 88, 14.7005, -17.4455),
('Arrêt Cité Assemblée', 89, 14.735, -17.468),
('Arrêt Sicap Liberté', 90, 14.7005, -17.45),
('Arrêt Baobab', 91, 14.716, -17.456),
('Arrêt Terminus Ouakam', 92, 14.715, -17.482),
('Arrêt Cité Aliou Sow', 93, 14.737, -17.365),
('Arrêt Cité Millionnaire', 94, 14.746, -17.345),
('Arrêt Diokoul', 95, 14.71, -17.26),
('Arrêt Arafat', 96, 14.73, -17.275);

-- ---------------------------------------------------------------------
-- LIGNE_ARRETS
-- ---------------------------------------------------------------------
INSERT INTO ligne_arrets (id_ligne, id_arret, ordre) VALUES
(1, 2, 1),
(1, 4, 2),
(1, 24, 3),
(1, 73, 4),
(1, 68, 5),
(1, 71, 6),
(2, 1, 1),
(2, 27, 2),
(2, 39, 3),
(2, 60, 4),
(2, 63, 5),
(2, 66, 6),
(3, 2, 1),
(3, 20, 2),
(3, 17, 3),
(3, 18, 4),
(4, 2, 1),
(4, 40, 2),
(4, 76, 3),
(4, 87, 4),
(4, 85, 5),
(5, 14, 1),
(5, 16, 2),
(5, 17, 3),
(5, 21, 4),
(5, 48, 5),
(6, 2, 1),
(6, 25, 2),
(6, 68, 3),
(6, 74, 4),
(6, 80, 5),
(7, 12, 1),
(7, 83, 2),
(7, 89, 3),
(7, 90, 4),
(8, 12, 1),
(8, 25, 2),
(8, 22, 3),
(8, 39, 4),
(8, 45, 5),
(8, 58, 6),
(8, 62, 7),
(8, 66, 8),
(9, 14, 1),
(9, 22, 2),
(9, 45, 3),
(9, 62, 4),
(9, 66, 5),
(10, 14, 1),
(10, 40, 2),
(10, 90, 3),
(10, 91, 4),
(10, 96, 5),
(11, 12, 1),
(11, 5, 2),
(11, 41, 3),
(11, 76, 4),
(11, 85, 5),
(12, 6, 1),
(12, 3, 2),
(12, 20, 3),
(12, 17, 4),
(12, 48, 5),
(13, 14, 1),
(13, 5, 2),
(13, 24, 3),
(13, 73, 4),
(13, 68, 5),
(14, 3, 1),
(14, 10, 2),
(14, 27, 3),
(14, 24, 4),
(14, 44, 5),
(15, 12, 1),
(15, 5, 2),
(15, 24, 3),
(15, 73, 4),
(15, 69, 5),
(15, 72, 6),
(15, 74, 7),
(16, 6, 1),
(16, 5, 2),
(16, 57, 3),
(16, 78, 4),
(16, 79, 5),
(17, 12, 1),
(17, 20, 2),
(17, 17, 3),
(17, 48, 4),
(17, 49, 5),
(17, 53, 6),
(18, 14, 1),
(18, 22, 2),
(18, 47, 3),
(18, 55, 4),
(18, 53, 5),
(19, 5, 1),
(19, 27, 2),
(19, 26, 3),
(19, 28, 4),
(19, 44, 5),
(20, 3, 1),
(20, 10, 2),
(20, 30, 3),
(20, 32, 4),
(20, 35, 5),
(21, 13, 1),
(21, 24, 2),
(21, 26, 3),
(21, 39, 4),
(22, 6, 1),
(22, 5, 2),
(22, 40, 3),
(22, 41, 4),
(23, 3, 1),
(23, 8, 2),
(23, 10, 3),
(23, 16, 4),
(24, 12, 1),
(24, 31, 2),
(24, 38, 3),
(24, 36, 4),
(25, 4, 1),
(25, 27, 2),
(25, 28, 3),
(25, 29, 4),
(26, 13, 1),
(26, 34, 2),
(26, 22, 3),
(26, 21, 4),
(26, 51, 5),
(26, 52, 6),
(27, 6, 1),
(27, 25, 2),
(27, 43, 3),
(27, 46, 4),
(28, 3, 1),
(28, 10, 2),
(28, 24, 3),
(28, 45, 4),
(29, 12, 1),
(29, 43, 2),
(29, 61, 3),
(29, 58, 4),
(29, 57, 5),
(30, 5, 1),
(30, 39, 2),
(30, 46, 3),
(30, 55, 4),
(30, 56, 5),
(31, 14, 1),
(31, 22, 2),
(31, 55, 3),
(31, 53, 4),
(31, 54, 5),
(32, 44, 1),
(32, 46, 2),
(32, 61, 3),
(32, 59, 4),
(33, 14, 1),
(33, 45, 2),
(33, 59, 3),
(33, 62, 4),
(33, 63, 5),
(34, 4, 1),
(34, 24, 2),
(34, 41, 3),
(34, 73, 4),
(35, 13, 1),
(35, 41, 2),
(35, 73, 3),
(35, 69, 4),
(35, 77, 5),
(36, 7, 1),
(36, 4, 2),
(36, 73, 3),
(36, 68, 4),
(36, 72, 5),
(37, 3, 1),
(37, 20, 2),
(37, 19, 3),
(37, 37, 4),
(38, 14, 1),
(38, 9, 2),
(38, 17, 3),
(38, 16, 4),
(38, 55, 5),
(38, 56, 6),
(39, 51, 1),
(39, 53, 2),
(39, 57, 3),
(39, 60, 4),
(39, 62, 5),
(39, 66, 6),
(40, 5, 1),
(40, 39, 2),
(40, 59, 3),
(40, 65, 4),
(40, 64, 5),
(41, 13, 1),
(41, 25, 2),
(41, 68, 3),
(41, 75, 4),
(42, 13, 1),
(42, 40, 2),
(42, 42, 3),
(42, 81, 4),
(42, 83, 5),
(43, 67, 1),
(43, 64, 2),
(43, 74, 3),
(43, 79, 4),
(44, 68, 1),
(44, 72, 2),
(44, 75, 3),
(45, 48, 1),
(45, 50, 2),
(45, 24, 3),
(45, 73, 4),
(45, 68, 5),
(45, 76, 6),
(46, 48, 1),
(46, 21, 2),
(46, 22, 3),
(46, 39, 4),
(46, 81, 5),
(46, 83, 6),
(47, 80, 1),
(47, 84, 2),
(47, 74, 3),
(47, 79, 4),
(48, 12, 1),
(48, 33, 2),
(48, 25, 3),
(48, 68, 4),
(48, 63, 5),
(48, 67, 6),
(49, 14, 1),
(49, 43, 2),
(49, 46, 3),
(49, 55, 4),
(49, 52, 5),
(50, 85, 1),
(50, 88, 2),
(50, 89, 3),
(51, 86, 1),
(51, 87, 2),
(51, 92, 3),
(52, 90, 1),
(52, 91, 2),
(53, 80, 1),
(53, 84, 2),
(53, 92, 3),
(54, 69, 1),
(54, 75, 2),
(54, 84, 3),
(54, 80, 4),
(55, 76, 1),
(55, 77, 2),
(55, 84, 3),
(55, 80, 4),
(56, 66, 1),
(56, 64, 2),
(56, 65, 3),
(56, 80, 4),
(57, 93, 1),
(57, 92, 2),
(58, 92, 1),
(58, 89, 2),
(58, 94, 3),
(59, 86, 1),
(59, 88, 2),
(59, 89, 3),
(59, 90, 4),
(60, 4, 1),
(60, 72, 2),
(60, 79, 3),
(60, 95, 4),
(61, 63, 1),
(61, 64, 2),
(61, 74, 3),
(61, 79, 4),
(62, 6, 1),
(62, 5, 2),
(62, 10, 3),
(62, 16, 4),
(62, 17, 5),
(63, 5, 1),
(63, 30, 2),
(63, 31, 3),
(63, 38, 4),
(64, 48, 1),
(64, 50, 2),
(64, 41, 3),
(64, 76, 4),
(64, 85, 5),
(65, 12, 1),
(65, 4, 2),
(65, 26, 3),
(65, 23, 4),
(66, 3, 1),
(66, 1, 2),
(66, 11, 3),
(67, 55, 1),
(67, 56, 2),
(67, 47, 3),
(67, 22, 4),
(68, 43, 1),
(68, 46, 2),
(68, 59, 3),
(68, 57, 4),
(69, 60, 1),
(69, 62, 2),
(69, 67, 3),
(69, 74, 4);




-- ---------------------------------------------------------------------
-- PHRASES EN WOLOF 
-- ---------------------------------------------------------------------
INSERT INTO phrases_wolof (wolof, francais, phonetique, situation) VALUES
('Salaam aleekum',        'Bonjour / La paix soit avec vous',            'sa-lam a-lé-koum',   'Salutations'),
('Maleekum salaam',       'Réponse à la salutation (paix sur vous aussi)', 'ma-lé-koum sa-lam', 'Salutations'),
('Nanga def ?',           'Comment vas-tu ?',                             'na-nga déf',         'Salutations'),
('Maa ngi fi',            'Je suis ici / Ça va bien (réponse)',           'ma-ngi-fi',          'Salutations'),
('Ana yow ?',             'Et toi, comment ça va ?',                      'a-na yow',           'Salutations'),
('Ba beneen yoon',        'À la prochaine fois',                          'ba bé-nén yoon',     'Salutations'),
('Ballago',               'Au revoir (forme familière)',                  'ba-la-go',           'Salutations'),
('Jërejëf',               'Merci',                                        'djé-ré-djef',        'Politesse'),
('Waaw',                  'Oui',                                          'waaw',               'Politesse'),
('Déedéet',               'Non',                                          'dé-dét',             'Politesse'),
('Baal ma',               'Excusez-moi / Pardon',                         'ba-al ma',           'Politesse'),
('Amul solo',             'Ce n''est rien / Pas de problème',             'a-moul so-lo',       'Politesse'),
('Ndank ndank',           'Doucement, doucement (expression de patience)', 'ndank ndank',       'Politesse'),
('Ma mangi dem',          'Je m''en vais / Au revoir',                    'ma man-gi dem',      'Salutations'),
('Nak bu baax ?',         'C''est combien ?',                             'nak boo baax',       'Négociation'),
('Ñaata la ?',            'Combien ça coûte ? (variante)',                'nya-ta la',          'Négociation'),
('Dafa seer',             'C''est trop cher',                             'da-fa sèr',          'Négociation'),
('Dafa seer lool',        'C''est vraiment trop cher',                    'da-fa sèr lool',     'Négociation'),
('Baax na',               'C''est bon, d''accord',                        'baax na',            'Négociation'),
('Dina dem',              'Je vais partir (si le prix n''est pas accepté)', 'di-na dem',        'Négociation'),
('Dem ci [lieu]',         'Aller à [lieu]',                               'dem si [lieu]',      'Transport'),
('Taxawal fii !',         'Arrêtez-vous ici !',                           'ta-xa-wal fi',       'Transport'),
('Yëgël ma ci...',        'Déposez-moi à...',                             'yé-guél ma si...',   'Transport'),
('Kañ nga dem ?',         'Quand pars-tu ?',                              'kagn nga dem',       'Transport'),
('Bus bi dafa fees',      'Le bus est plein',                             'bous bi da-fa fès',  'Transport'),
('Ana taxi yi ?',         'Où sont les taxis ?',                          'a-na tak-si yi',     'Transport'),
('Fan la [lieu] nekk ?',  'Où se trouve [lieu] ?',                        'fan la [lieu] nèk',  'Direction'),
('Jëm ci kanam',          'Aller tout droit',                             'djèm si ka-nam',     'Direction'),
('Jëm ci ndey',           'Tourner à gauche',                             'djèm si ndèy',       'Direction'),
('Jëm ci kaw',            'Tourner à droite',                             'djèm si kaw',        'Direction'),
('Yagg na ?',             'C''est loin ?',                                'yagg na',            'Direction'),
('Foofu la',              'C''est là-bas',                                'fo-fu la',           'Direction'),
('Fii la',                'C''est ici',                                   'fi la',              'Direction'),
('Benn, ñaar, ñett',      'Un, deux, trois',                              'bèn, nyar, nyèt',    'Nombres'),
('Ñeent, juróom',         'Quatre, cinq',                                 'nyènt, dju-rom',     'Nombres'),
('Juróom-benn',           'Six',                                          'dju-rom-bèn',        'Nombres'),
('Fukk',                  'Dix',                                          'fouk',               'Nombres'),
('Dama metti',            'J''ai mal / Je souffre',                       'da-ma mét-ti',       'Urgence'),
('Wóoy !',                'Au secours ! (exclamation de détresse)',       'wooy',               'Urgence'),
('Sama xel dafa tang',    'Je suis stressé(e) / inquiet(ète)',            'sa-ma xèl da-fa tang', 'Urgence');

-- ---------------------------------------------------------------------
-- CONSEILS 
-- ---------------------------------------------------------------------
INSERT INTO conseils (categorie, titre, contenu, periode) VALUES
('Avant de partir',     'Prévoir de la monnaie',            'Ayez toujours des petites coupures : les chauffeurs n''ont pas toujours la monnaie sur un gros billet.', 'Toute l''année'),
('Avant de partir',     'Vêtements adaptés',                'Porter des vêtements légers mais couvrants, par respect culturel.', 'Toute l''année'),
('Dans le transport',   'Négocier avant de monter',         'Pour les taxis clando, toujours fixer le prix avant de monter, jamais après.', 'Toute l''année'),
('Dans le transport',   'Vérifier la destination',          'Confirmer la destination avec le chauffeur avant de partir pour éviter tout malentendu.', 'Toute l''année'),
('Confort et bien-être','Climatisation non garantie',       'La climatisation n''est pas garantie dans tous les taxis ni dans les cars rapides.', 'Toute l''année'),
('Confort et bien-être','Se protéger du soleil',            'Utiliser un chapeau ou un parasol en cas de fort ensoleillement.', 'Toute l''année'),
('Argent et paiement',  'Montant fixe pour le DDD et le BRT', 'Le bus Dakar Dem Dikk et le BRT appliquent un tarif fixe, pas de négociation nécessaire.', 'Toute l''année'),
('Argent et paiement',  'Éviter de montrer trop d''argent',  'Sortez uniquement la somme nécessaire au moment de payer.', 'Toute l''année'),
('Saisons et météo',    'Prévoir du temps en saison des pluies', 'Les jours de pluie (juillet à octobre), prévoyez le double du temps de trajet habituel.', 'Météo'),
('Saisons et météo',    'Circulation dense le vendredi',    'La circulation peut être très dense le vendredi après-midi, lors du retour du travail et de la prière.', 'Heures de pointe'),
('Saisons et météo',    'Éviter les heures de pointe',      'Les heures de pointe sont 7h-9h le matin et 17h-20h le soir : prévoir une marge.', 'Heures de pointe'),
('Pour les femmes',     'Privilégier les transports connus', 'Privilégier le TER, le BRT ou le DDD en soirée plutôt qu''un taxi inconnu.', 'Toute l''année'),
('Périodes',            'Affluence pendant les vacances',    'Pendant les vacances scolaires et les grands événements religieux (Magal, Tabaski), les gares routières sont bondées : réserver ou partir tôt.', 'Vacances');

-- ---------------------------------------------------------------------
-- INFOS UTILES 
-- ---------------------------------------------------------------------
INSERT INTO infos_utiles (categorie, libelle, valeur) VALUES
('Urgence', 'Police nationale',       '17'),
('Urgence', 'SAMU (urgences médicales)', '15'),
('Urgence', 'Sapeurs-pompiers',       '18'),
('Urgence', 'Gendarmerie nationale',  '800 00 20 20'),
('À emporter', 'Objet recommandé',    'Petite monnaie en FCFA'),
('À emporter', 'Objet recommandé',    'Chapeau ou casquette'),
('À emporter', 'Objet recommandé',    'Bouteille d''eau'),
('À emporter', 'Objet recommandé',    'Copie de vos papiers d''identité'),
('À emporter', 'Objet recommandé',    'Téléphone chargé + batterie externe'),
('À emporter', 'Objet recommandé',    'Crème solaire'),
('À emporter', 'Objet recommandé',    'Lingettes ou mouchoirs'),
('À emporter', 'Objet recommandé',    'Petit sac fermé, porté devant vous'),
('À emporter', 'Objet recommandé',    'Plan hors-ligne ou application de cartographie téléchargée');

-- ---------------------------------------------------------------------
-- ENRICHISSEMENT : nouveaux quartiers / sites touristiques
-- ---------------------------------------------------------------------
INSERT INTO lieux (nom, type_lieu, latitude, longitude, description) VALUES
('Yoff Layène', 'quartier', 14.7550, -17.4830, 'Quartier historique de la confrérie layène, en bord de mer à Yoff'),
('Cité Djily Mbaye', 'quartier', 14.7130, -17.4550, 'Cité résidentielle proche de Liberté 6 et Grand Yoff'),
('Liberté 6 Extension', 'quartier', 14.7225, -17.4680, 'Extension résidentielle de Liberté 6, vers la VDN'),
('Sacré-Cœur 3', 'quartier', 14.7145, -17.4700, 'Extension du quartier Sacré-Cœur'),
('Zac Mbao', 'quartier', 14.7430, -17.3510, 'Zone d''aménagement concerté proche de Mbao'),
('Cité Fadia', 'quartier', 14.7295, -17.4880, 'Quartier résidentiel proche d''Ouakam et Mermoz'),
('Yeumbeul Sud', 'quartier', 14.7620, -17.3800, 'Secteur sud de Yeumbeul'),
('Île de Ngor', 'site_touristique', 14.7508, -17.5177, 'Petite île accessible en pirogue depuis le village de Ngor, plages préservées'),
('Monument de la Renaissance Africaine', 'site_touristique', 14.7203, -17.4890, 'Statue monumentale surplombant Ouakam, l''une des plus hautes d''Afrique'),
('Village des Arts', 'site_touristique', 14.7245, -17.4820, 'Centre d''art contemporain et ateliers d''artistes à Ouakam'),
('Île de la Madeleine', 'site_touristique', 14.6656, -17.4791, 'Îlot classé parc national, réserve d''oiseaux marins'),
('Gare de Dakar', 'gare', 14.6743, -17.4372, 'Ancienne gare ferroviaire de Dakar, à proximité du Plateau');

-- ---------------------------------------------------------------------
-- ENRICHISSEMENT : nouvelles phrases wolof
-- ---------------------------------------------------------------------
INSERT INTO phrases_wolof (wolof, francais, phonetique, situation) VALUES
('Jamm ak jamm', 'Tout va bien (réponse classique à « Nanga def ? »)', 'diam ak diam', 'Salutations'),
('Naka nga tudd ?', 'Comment tu t''appelles ?', 'na-ka nga toud', 'Salutations'),
('Su la neexee', 'S''il te plaît', 'sou la né-é', 'Politesse'),
('Baal ma, dama bëgg laa laaj', 'Excusez-moi, je voudrais vous demander', 'baal ma dama beug la ladj', 'Politesse'),
('Wesaare', 'Faire la monnaie / rendre la monnaie', 'wé-sa-ré', 'Négociation'),
('Dafa yomb', 'C''est raisonnable, pas cher', 'da-fa yomb', 'Négociation'),
('Dama bëgg dem [lieu]', 'Je voudrais aller à [lieu]', 'da-ma beug dem', 'Transport'),
('Ban gaal moo dem [lieu] ?', 'Quel véhicule va à [lieu] ?', 'ban gaal mo dem', 'Transport'),
('Fan la gare bi nekk ?', 'Où se trouve la gare routière ?', 'fan la gar bi nèk', 'Transport'),
('Wàcc fi !', 'Descendez ici !', 'watch fi', 'Direction'),
('Ci kanam rekk', 'Continuez tout droit', 'ci ka-nam rèk', 'Direction'),
('Fukk ak juróom', 'Quinze', 'fouk ak dioróm', 'Nombres'),
('Téeméer', 'Cent', 'té-mér', 'Nombres'),
('Wallal ma !', 'Aidez-moi !', 'wa-lal ma', 'Urgence'),
('Fabu police bi', 'Appelez la police', 'fabou po-lis bi', 'Urgence');

-- ---------------------------------------------------------------------
-- ENRICHISSEMENT : nouvelles lignes minibus (Tata/AFTU) + arrêts
-- Utilise des sous-requêtes par nom pour rester valide quelle que soit
-- la numérotation exacte des lignes/lieux déjà insérés ci-dessus.
-- ---------------------------------------------------------------------
INSERT INTO lignes_bus (numero_ligne, nom_ligne, id_transport, est_minibus, description) VALUES
('Ligne 23', 'Petersen - Yoff Layène', (SELECT id_transport FROM moyens_transport WHERE nom LIKE 'Minibus Tata%'), 1, 'Minibus Tata (AFTU) reliant Petersen à Yoff Layène via Sacré-Cœur, Ouest Foire, Yoff'),
('Ligne 31', 'Grand Yoff - Cité Djily Mbaye', (SELECT id_transport FROM moyens_transport WHERE nom LIKE 'Minibus Tata%'), 1, 'Minibus Tata (AFTU) reliant Grand Yoff à Cité Djily Mbaye via Liberté 6, Liberté 6 Extension'),
('Ligne 33', 'Ouakam - Village des Arts', (SELECT id_transport FROM moyens_transport WHERE nom LIKE 'Minibus Tata%'), 1, 'Minibus Tata (AFTU) reliant Ouakam au Village des Arts via Virage Ouakam et le Monument de la Renaissance Africaine'),
('Ligne 51', 'Colobane - Zac Mbao', (SELECT id_transport FROM moyens_transport WHERE nom LIKE 'Minibus Tata%'), 1, 'Minibus Tata (AFTU) reliant Colobane à Zac Mbao via Hann, Mbao, Petit Mbao'),
('Ligne 61', 'Pikine - Yeumbeul Sud', (SELECT id_transport FROM moyens_transport WHERE nom LIKE 'Minibus Tata%'), 1, 'Minibus Tata (AFTU) reliant Pikine à Yeumbeul Sud via Thiaroye, Yeumbeul'),
('Ligne 68', 'Médina - Gare de Dakar', (SELECT id_transport FROM moyens_transport WHERE nom LIKE 'Minibus Tata%'), 1, 'Minibus Tata (AFTU) reliant Médina à la Gare de Dakar via Tilène, Plateau');

INSERT INTO arrets (nom, id_lieu, latitude, longitude) VALUES
('Arrêt Petersen (L23)', (SELECT id_lieu FROM lieux WHERE nom='Petersen'), 14.6759, -17.4373),
('Arrêt Sacré-Cœur (L23)', (SELECT id_lieu FROM lieux WHERE nom='Sacré-Cœur'), 14.7186, -17.4638),
('Arrêt Ouest Foire (L23)', (SELECT id_lieu FROM lieux WHERE nom='Ouest Foire'), 14.742, -17.475),
('Arrêt Yoff (L23)', (SELECT id_lieu FROM lieux WHERE nom='Yoff'), 14.7444, -17.4677),
('Arrêt Yoff Layène', (SELECT id_lieu FROM lieux WHERE nom='Yoff Layène'), 14.7550, -17.4830),
('Arrêt Grand Yoff (L31)', (SELECT id_lieu FROM lieux WHERE nom='Grand Yoff'), 14.7364, -17.4569),
('Arrêt Liberté 6 (L31)', (SELECT id_lieu FROM lieux WHERE nom='Liberté 6'), 14.711, -17.4577),
('Arrêt Liberté 6 Extension', (SELECT id_lieu FROM lieux WHERE nom='Liberté 6 Extension'), 14.7225, -17.4680),
('Arrêt Cité Djily Mbaye', (SELECT id_lieu FROM lieux WHERE nom='Cité Djily Mbaye'), 14.7130, -17.4550),
('Arrêt Ouakam (L33)', (SELECT id_lieu FROM lieux WHERE nom='Ouakam'), 14.7167, -17.4833),
('Arrêt Virage Ouakam (L33)', (SELECT id_lieu FROM lieux WHERE nom='Virage Ouakam'), 14.72, -17.478),
('Arrêt Monument de la Renaissance', (SELECT id_lieu FROM lieux WHERE nom='Monument de la Renaissance Africaine'), 14.7203, -17.4890),
('Arrêt Village des Arts', (SELECT id_lieu FROM lieux WHERE nom='Village des Arts'), 14.7245, -17.4820),
('Arrêt Cité Fadia', (SELECT id_lieu FROM lieux WHERE nom='Cité Fadia'), 14.7295, -17.4880),
('Arrêt Colobane (L51)', (SELECT id_lieu FROM lieux WHERE nom='Colobane'), 14.6812, -17.4423),
('Arrêt Hann (L51)', (SELECT id_lieu FROM lieux WHERE nom='Hann'), 14.722, -17.429),
('Arrêt Mbao (L51)', (SELECT id_lieu FROM lieux WHERE nom='Mbao'), 14.735, -17.335),
('Arrêt Petit Mbao (L51)', (SELECT id_lieu FROM lieux WHERE nom='Petit Mbao'), 14.74, -17.33),
('Arrêt Zac Mbao', (SELECT id_lieu FROM lieux WHERE nom='Zac Mbao'), 14.7430, -17.3510),
('Arrêt Pikine (L61)', (SELECT id_lieu FROM lieux WHERE nom='Pikine'), 14.7547, -17.39),
('Arrêt Thiaroye (L61)', (SELECT id_lieu FROM lieux WHERE nom='Thiaroye'), 14.7639, -17.3592),
('Arrêt Yeumbeul (L61)', (SELECT id_lieu FROM lieux WHERE nom='Yeumbeul'), 14.77, -17.365),
('Arrêt Yeumbeul Sud', (SELECT id_lieu FROM lieux WHERE nom='Yeumbeul Sud'), 14.7620, -17.3800),
('Arrêt Médina (L68)', (SELECT id_lieu FROM lieux WHERE nom='Médina'), 14.6708, -17.4467),
('Arrêt Tilène (L68)', (SELECT id_lieu FROM lieux WHERE nom='Tilène'), 14.679, -17.446),
('Arrêt Plateau (L68)', (SELECT id_lieu FROM lieux WHERE nom='Plateau'), 14.6708, -17.4313),
('Arrêt Gare de Dakar', (SELECT id_lieu FROM lieux WHERE nom='Gare de Dakar'), 14.6743, -17.4372);

INSERT INTO ligne_arrets (id_ligne, id_arret, ordre) VALUES
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 23'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Petersen (L23)'), 1),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 23'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Sacré-Cœur (L23)'), 2),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 23'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Ouest Foire (L23)'), 3),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 23'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Yoff (L23)'), 4),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 23'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Yoff Layène'), 5),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 31'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Grand Yoff (L31)'), 1),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 31'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Liberté 6 (L31)'), 2),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 31'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Liberté 6 Extension'), 3),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 31'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Cité Djily Mbaye'), 4),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 33'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Ouakam (L33)'), 1),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 33'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Virage Ouakam (L33)'), 2),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 33'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Monument de la Renaissance'), 3),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 33'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Village des Arts'), 4),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 33'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Cité Fadia'), 5),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 51'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Colobane (L51)'), 1),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 51'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Hann (L51)'), 2),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 51'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Mbao (L51)'), 3),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 51'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Petit Mbao (L51)'), 4),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 51'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Zac Mbao'), 5),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 61'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Pikine (L61)'), 1),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 61'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Thiaroye (L61)'), 2),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 61'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Yeumbeul (L61)'), 3),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 61'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Yeumbeul Sud'), 4),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 68'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Médina (L68)'), 1),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 68'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Tilène (L68)'), 2),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 68'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Plateau (L68)'), 3),
((SELECT id_ligne FROM lignes_bus WHERE numero_ligne='Ligne 68'), (SELECT id_arret FROM arrets WHERE nom='Arrêt Gare de Dakar'), 4);